### ISSUE TITLE
another test case that results in long connectors

### ISSUE THREAD

**Issue by uliw** [terrastruct/TALA#19]
Note, this may be well outside the scope of what tala tries to achieve since it describes geometric relationships,  but I post here it here in case it is useful.

The code below results in some unnecessarily long connectors.

```
D: D:{
A
I
P}

M :M:{
A
I
P
}

S: L: {
A
I
P
H
}


# Surface Intermediate Mixing
S.A <-> M.A
S.I <-> M.I
S.P <-> M.P

# THC downwelling
S.H -> D.A

# THC advection
D.A -> D.I
D.I -> D.P
M.P -> M.I
M.I -> M.A

# THC Upwelling
M.A <- D.A
M.I <- D.I
M.P <- D.P
M.A -> S.H
```

**Comment by alixander** [comment]
latest release has this looking a lot better. looks like a node can still be improved though, should be 💯 by next release. thanks for these @uliw 

https://play.d2lang.com/?script=bJLBasMwEETv-xUDPXs_QBSDqA4SdEGg9gNMrAQf4gTjxIGQfw9eyQRCbsMM8xiWdQbO4E6AJSAQEOlBJAbywU4Gv-824NfoC-ky7btdRhjnPB1zP3Rzhgy3YTxQYovvpoWwpcSh6kCJY9VxRfz5H_SnZVz04mvNo2nh2G5p11_LI5BjW7JAjkORkYQjKluKK6_y_3kDi-5RsOgc5YiuqRylJ_b0DAAA__8%3D&layout=tala&

**Comment by uliw** [comment]
Thx! This is very promising!

**Comment by drewbitt** [comment]
Seems fixed
