### ISSUE TITLE
err: Timed out: EdgeRouting

### ISSUE THREAD

**Issue by hsuominen** [terrastruct/TALA#20]
On routing a somewhat complex process flow diagram with order 100 nodes (but less than 200) the edge routing times out with:

> err: Timed out: EdgeRouting 

Unfortunately I am not able to share the failing example and wasn't able to quickly generate a minimal reproducible example.

Both ELK and dagre fare fine with this case, but do generate quite wide diagrams.

**Comment by jamestiotio** [comment]
To address this error, perhaps allowing the user to specify a larger timeout value might be feasible.

**Comment by drewbitt** [comment]
Likely fixed, and you can specify a larger timeout now 

d2 --timeout 200 large.d2
