### ISSUE TITLE
Tala improvement suggestion: reduce empty space

### ISSUE THREAD

**Issue by judepayne** [terrastruct/TALA#27]
Hi,
On large diagrams, Tala introduces quite a lot of empty space.
Would it be possible to introduce a setting to 'compress' the space?

![image](https://user-images.githubusercontent.com/141360/215058249-44b8ba4a-2372-4135-99cd-be4d9ecd2b2d.png)

**Comment by alixander** [comment]
most recent TALA release has an improvement related to this. can you try rerunning? (or post the script if it's still bad) @judepayne

**Comment by judepayne** [comment]
Thanks @alixander I have played with this and large diagrams like above that previously could have too much space, now have a lot less and look a lot better!

**Comment by gavin-ts** [comment]
> ... here's another one 

as a playground link: 
https://play.d2lang.com/?script=jFNBTsMwELznFfMBohZKU3xAKoVKXCknbsZZwGpiG8cRINS_I6chdYJbcrO8O7OzM_YzV1uG7wRY1yqv9keAG7OYzjOGW-44No3soHDFsC54SSil0vZQyKYMj5bnBGO1oSIBdgnwIKttn3nGsLKUS4fXmtu87VvLT8pxr4Quqd8_P6IkmwwLnmelrdGWuwHJgjVKsHkjcgHHOcPScIFlR3D3XksnaWDHJcON1lvk-kN1ihVXoj8nu2B40oqga9e07RLvctqpSls5OLtGvMIgCknKoeSVI7vHe-1tw-wY1O_Ci0IL7j9LdQLYxJ12cUr_22rxHyqi1Pm8W0xAmk0Po4JY0y7PkRPDy6gtvUWi62WxYX9FZZNTrhpdybHwwfCKRG2l-4KlF7KkBI3hGGla3PLfB5x2L3eoP55UeBtifgIAAP__&layout=tala&

**Comment by alixander** [comment]
@gavin-ts i think our parameters just considers this okay. e.g. grid cell is large because of the containers. i suspect if we just lower the threshold it'll be okay
