### ISSUE TITLE
TALA seed in the source file

### ISSUE THREAD

**Issue by Filip-K** [terrastruct/TALA#40]
Hi! I just thought it would be nice to have the option of specifying the TALA seed in the source file. This would make diagrams created with TALA more reproducible. Now, if somebody makes a diagram and finds a seed that yields a particularly nice result, the diagram cannot be readily reproduced even in the same version of TALA (unless the author notes the seed in a comment).

**Comment by mauroexe** [comment]
It a great idea, have you worked on it Alixander?

I'm trying to implement your project on my entire company, it does great diagrams but needs to be refined and to have more error handling and more options in the command line.

**Comment by alixander** [comment]
@mauroexe you can specify the seed via command line, but it's a good idea to also be able to specify that in the source file. Now that `vars` configurations works, it'll be easy to add this. 

> error handling and more options in the command line.

Can you let me know what they are? Hoping to do some while I'm doing this.

**Comment by Didas-git** [comment]
+1
Would be amazing to be able to add predictability or to just force using less resources this way, and i think one great advantage that could come with this is when using `--watch` seeing the changes happen to make it easier to choose

**Comment by mauroexe** [comment]
> @mauroexe you can specify the seed via command line, but it's a good idea to also be able to specify that in the source file. Now that `vars` configurations works, it'll be easy to add this.
> 
> > error handling and more options in the command line.
> 
> Can you let me know what they are? Hoping to do some while I'm doing this.

Error Handling:

I encountered an error after running the --watch command. After several days of troubleshooting, I believe the antivirus might be blocking access to files the command needs to function properly. Unfortunately, I don't have access to the antivirus logs, so I cannot identify the specific files being blocked.

D2Lang Documentation:

While reviewing the D2Lang online documentation for the seed parameter, I noticed a discrepancy:

Online Documentation: Lists "seed" (singular)

![image](https://github.com/terrastruct/TALA/assets/59969035/363b84dd-297f-4547-b3ea-ee8ce4934ce4)
https://d2lang.com/tour/tala/

User Manual: Correctly uses "seeds" (plural)

![image](https://github.com/terrastruct/TALA/assets/59969035/0c551507-e367-4287-b5ce-ace595390ba0)
https://github.com/terrastruct/TALA/blob/master/TALA_User_Manual.pdf

This inconsistency caused some confusion, as it took me time to discover the correct usage, also the D2Lang docs doesn't mention that you can pass more than one seed; to improve the documentation, I recommend adding a direct link to the User Manual from the D2Lang online documentation, allowing users to access more detailed information.

**Comment by mauroexe** [comment]
Hey Alixander!

Could it be possible to show the selected seed by the algorithm as info when compiling?

**Comment by alixander** [comment]
@mauroexe oh good find on that flag discrepency. It was updated in a release and looks like I forgot to update the docs to reflect it.

https://github.com/terrastruct/TALA/releases/tag/v0.3.4

The docs online are just a preview, I should make it clear the canonical source is the manual.

> I encountered an error after running the --watch command.

What was the error? The CLI should have sufficient logs to inform the user if it's a file permissioning issue.

**Comment by alixander** [comment]
will be in next release

**Comment by Filip-K** [comment]
Just to have the solution in plain text for anyone who might come here, it seems that the way to specify the seed in the source file is
```d2
vars: {
  d2-config: {
    tala-seeds: 1
  }
}
```

Incidentally, it does not seem work in the Playground at the moment (`3:5: "tala-seeds" is not a valid config`). Is there something that I'm missing?

**Comment by alixander** [comment]
I've cut new releases, but unfortunately I made a mistake for this release, so this won't be available until the next version, apologies all. 

It's available on d2 playground though, which runs master.

[A layout with one seed](https://play.d2lang.com/?script=rFU9b9s8EN71K24x8L6DP6oCHTgUkKU20JBUQFpkqDuc5YtCRD4SJO0gDfzfC1KSEzuSUQEdbPGOx4cP73OPxgp4iQA28bRUfC-rRgTYoMNuDeCwxqkl2lgBP1sdwIdP7fJX-B4i_ztEUVmjtdQho31IFTOVTiruIK17rmlmnVGPNPUmAj52x39YMo2dLP2JB-e0FfO5l-zMkTFondmVblaq7Rx_7wzNr4jJYD2JF7dk9rKkSbzIvf38-5OaxAuP2apmdl9FAPYBNQmQW6zI33oruaqpwIruaJ1oLaDRTDVWBE-0XjGg1iN53dH6hFOqamXmidYn2kxtUbIdYJaUTu4pk4ZKp8yzgEYBR81ITvmG2En33EcsIHtGHfaQtxw6WaaKHbET0IhQNnLgk2Y3wv-1Af97ejfknpR5lFz1EEyzm0m8KIy6lzV1Djuj59MoAljWan3rlMGKRBCglUYzytDhGi3ZHkIe2Ksb6GFCJ3xg-tm7JgS3yAUkRR5IJUV-jYwVbYlde5Nttl_1K-52Rj8kZ0eVQV-IfcEv8km8eL3o1eSyo7_uONR2KJpOgETr_-z_oymmaqt3jnrodciTeJFofZlSquxW2Wwp2hVky38a9cRbBMmj-3pZXgp9b1x9Erxx3akjQ4a0jwhp4i8spKZask-JNJ-nGewlQtiBFcNxd2Q7yGj_TV965BG4rxcAMKHpOkDbEKJDdK1YOmUEfOHN1Kkp8QZWvG20kqvAfcUN-9Z4JPGTTEXeTOLFldqTYeSyL4HaWy69IinybgL5CJzPhOPGu5b8EmaeOJt2h3dTJaC-ddXM94E-q6TIZ715cz4POuOTMhziM3B2oPEMofwJAAD__w%3D%3D&layout=tala&)

vars: {
  d2-config: {
    data: {
      tala-seeds: [
        17
        18
        19
      ]
    }
  }
}

classes: {
  dashConnection: {
    style.stroke-dash: 3
  }
}

User: {
  icon: https://icons.terrastruct.com/azure/General%20Service%20Icons/Two%20User%20Icon.svg
  shape: image
}

SinglePageWebApp: Single-page web\n app {
  icon: https://icons.terrastruct.com/azure/Web%20Service%20Color/App%20Service%20Domains.svg
  shape: image
}

ActiveDirectory: Active Directory {
  icon: https://icons.terrastruct.com/azure/Identity%20Service%20Color/Active%20Directory.svg
  shape: image
}

StaticContent: Static content {
  CDN: CDN {
    icon: https://icons.terrastruct.com/azure/Networking%20Service%20Color/CDN%20Profiles.svg
    shape: image
  }

  BlobStorage: Blob Storage {
    icon: https://icons.terrastruct.com/azure/Databases%20Service%20Color/Blob%20Storage.svg
    shape: image
  }
  BlobStorage -> CDN
}

API: API {
  APIManagementServices: API Management\nServices {
    icon: https://icons.terrastruct.com/azure/Integration%20Service%20Color/API%20Management%20Services.svg
    shape: image
  }

  FunctionApp: Function App(s) {
    icon: https://icons.terrastruct.com/azure/Compute%20Service%20Color/Function%20Apps.svg
    shape: image
  }

  CosmosDB: Cosmos DB {
    icon: https://icons.terrastruct.com/azure/Databases%20Service%20Color/Azure%20Cosmos%20DB.svg
    shape: image
  }
  APIManagementServices -> FunctionApp
  FunctionApp -> CosmosDB
}

AzurePipelines: CI/CD via Azure \n Pipelines {
  icon: https://icons.terrastruct.com/azure/DevOps%20Service%20Color/Azure%20Pipelines.svg
  shape: image
  near: StaticContent
}
Monitor: End-to-end \nmonitoring via \nAzure Monitor {
  icon: https://icons.terrastruct.com/azure/Management%20and%20Governance%20Service%20Color/Monitor.svg
  shape: image
  near: API
}

User -> SinglePageWebApp
User -> ActiveDirectory: {class: dashConnection}
SinglePageWebApp -> StaticContent.CDN
SinglePageWebApp -> API.APIManagementServices
ActiveDirectory -> API.FunctionApp: {class: dashConnection}
ActiveDirectory -> API.APIManagementServices: {class: dashConnection}
