### ISSUE TITLE
failed to verify $TSTRUCT_TOKEN: illegal base64 data at input byte 5

### ISSUE THREAD

**Issue by orange-buffalo** [terrastruct/TALA#67]
Hi,

We've just purchased TALA license and trying to integrate it into our CI. We provided `TSTRUCT_TOKEN` environment variable with one of the tokens we received. However, `d2plugin-tala --help` fails with:
```
[2024-02-12T22:03:41.916Z] WARNING: THIS COPY OF TALA IS UNLICENSED AND IS FOR EVALUATION PURPOSES ONLY

[2024-02-12T22:03:41.916Z] 

[2024-02-12T22:03:41.916Z] failed to verify $TSTRUCT_TOKEN: illegal base64 data at input byte 5
```
And our diagrams are generated with the watermark.

**Comment by alixander** [comment]
@orange-buffalo if you go to [playground](https://play.d2lang.com/?script=qlDQtVOo5AIEAAD__w%3D%3D&layout=tala&) and enter the key there, does it work?

<img width="1671" alt="Screenshot 2024-02-12 at 9 56 46 PM" src="https://github.com/terrastruct/TALA/assets/3120367/c48758a5-6b2d-4a9d-920c-9e9a18e18793">

**Comment by orange-buffalo** [comment]
I see this message and nothing in console/network tab, although I am connected to the Internet:

![image](https://github.com/terrastruct/TALA/assets/4532247/8da8ad34-14b0-4d4a-bc26-e18789517b5b)

So I assume it does not work.

**Comment by alixander** [comment]
@orange-buffalo can you try copying and pasting the key into a text editor and see if there are whitespaces? Sometimes when copying and pasting from a PDF, the newlines are preserved.

**Comment by orange-buffalo** [comment]
:facepalm: Indeed when copied from PDF it contains line breaks.. After cleaning them up we are able to use the tokens. Thanks for the hint. Maybe as an improvement the token PDF could be changed to avoid this issue, e.g. replacing table layout with block layout or something like that.
