### ISSUE TITLE
failed to compile: plugin has routing feature but does not implement RoutingPlugin

### ISSUE THREAD

**Issue by miroslav-matejovsky** [terrastruct/TALA#72]
when I start local server with

```
d2 -w simple.d2 --layout tala   
```

I get

```
failed to compile: plugin has routing feature but does not implement RoutingPlugin
```

<img width="1704" alt="Screenshot 2024-04-15 at 15 43 21" src="https://github.com/terrastruct/TALA/assets/1708543/86aadcd8-298d-48c4-8102-0968b158bca2">

Without tala I see diagram correctly:

```
d2 -w simple.d2
```

<img width="325" alt="Screenshot 2024-04-15 at 15 45 26" src="https://github.com/terrastruct/TALA/assets/1708543/94e9a657-6ef9-4bdd-a906-620f4a880bf9">

Content of `simple.d2`:

```d2
foo -> bar
```

**Comment by mauroexe** [comment]
I have the same problem.

I installed the latest d2 release for Windows, it was working correctly.

The issue happened just after installing the last TALA update.

**Comment by alixander** [comment]
Sorry about this. I've fixed this in d2's `master`, and plan to release tomorrow latest.

**Comment by alixander** [comment]
Please upgrade to https://github.com/terrastruct/d2/releases/tag/v0.6.5

**Comment by alixander** [comment]
Will leave open for a bit until verified fix

**Comment by miroslav-matejovsky-vissim** [comment]
working now, thanks @alixander
