### ISSUE TITLE
Please don't recommend to use this layout engine if it's not a one-line install...

### ISSUE THREAD

**Issue by olleharstedt** [terrastruct/TALA#73]
Getting this error

> WARNING: THIS COPY OF TALA IS UNLICENSED AND IS FOR EVALUATION PURPOSES ONLY
> missing api token: could not find $TSTRUCT_TOKEN or api_token in auth file ~/.config/tstruct/auth.json

Would be nice to get a warning before, now I have to reset my d2.

**Comment by alixander** [comment]
That's fair I'll add a note that it requires a license key in the README. 

> now I have to reset my d2.

You just uninstall TALA.
