### ISSUE TITLE
--animate-interval fails with unlicensed TALA

### ISSUE THREAD

**Issue by JonathanMbt** [terrastruct/TALA#85]
D2 version: v0.6.6
Tala version: v0.4.0

I'm trying to do a scenario composition w/ Tala algorithm and exporting it to a single animated SVG using the parameter `--animate-interval 1200` . But when I try to generate it:
```
err: failed to compile: exit status 1
err: stderr:
err: err: SVG missing viewbox
``` 
Executing the command with debug doesn't give more informations.

**Comment by alixander** [comment]
@JonathanMbt is it happening with all diagrams or a specific one?

**Comment by JonathanMbt** [comment]
It's seems to occur on all diagrams, even with the example in the documentation: https://d2lang.com/tour/scenarios

**Comment by alixander** [comment]
oh interesting it looks like the watermark adding code for unlicensed TALA interferes with animated SVGs.

thanks for this catch

**Comment by JonathanMbt** [comment]
Thanks for the fix !
